### PR TITLE
Features/add account switcher to orion

### PR DESCRIPTION
**Pull request by aneyzberg**
Add Project Account Switcher to Global Nav

## Description
This feature adds the account Switcher to the global Nav in Orion. Now users will be able to see their lists of accounts and projects in Orion

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shannonwells** [comment]
Does this need screencaps for the story & test files?

**Comment by aneyzberg** [comment]
It has test files. But yes. I should add a screen cap

**Comment by aneyzberg** [comment]
project-account-switcher-1

**Comment by aneyzberg** [comment]
project-account-switcher-storybook


This is the snapshot for storybook

**Pull request merged**
